### ISSUE TITLE
browser tab title changes to 'Odoo' once on the dashboard page

### ISSUE THREAD

**Issue by benoit-leveau** [cgstudiomap/cgstudiomap#181] opened 2015-07-15 17:15 UTC
The browser tab title reads 'cgstudiomap' on the main page but once logged in, it changes to the less useful 'Odoo'.

**Comment by foutoucour** [comment] 2015-07-15 19:04
Thank you @benoit-leveau !

The issue is coming from a customization of the `web.layout` template.
We had the same issue in the `website.layout` but we only solved in it...

To solve the issue, we need to do:
- create a new template in `main_data/templates/web_layout.xml`
``` xml
<template id="web.shared_title" name="Web Title">
    <title>cgstudiomap</title>
</template>
```
- call the template in `website.layout` (line 87) and `web.layout` (line 8). Should be something like:
``` xml
<t t-call="web.shared_title"/>
```

That should solve the current issue but also prevent to have to update the title in both templates

**Comment by M4rtine** [comment] 2015-07-16 05:21
Thanks @benoit-leveau

Le mercredi 15 juillet 2015, Jordi Riera <notifications@github.com> a
écrit :

> Thank you @benoit-leveau <https://github.com/benoit-leveau> !
>
> The issue is coming from a customization of the web.layout template.
> We had the same issue in the website.layout but we only solved in it...
>
> To solve the issue, we need to do:
>
>    - create a new template in main_data/templates/web_layout.xml
>
> <template id="web.shared_title" name="Web Title">
>     <title>cgstudiomap</title>
> </template>
>
>
>    - call the template in website.layout (line 87) and web.layout (line
>    8). Should be something like:
>
> <t t-call="web.shared_title"/>
>
> That should solve the current issue but also prevent to have to update the
> title in both templates
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cgstudiomap/cgstudiomap/issues/181#issuecomment-121714965>
> .
>


-- 

____________________________

*david.mazeau*
*06 64 19 11 50www.davidmazeau.com <http://www.davidmazeau.com>*

**Comment by foutoucour** [comment] 2015-07-16 12:32
I worked on it yesterday and it is not as simple as suspected.

The title is set by a javascript that is hidding somewhere in the code. Neede more investigation.

**Comment by foutoucour** [comment] 2015-11-26 01:24
Will be fixed by the switch to the new templates

**Closed by foutoucour** 2015-11-26 01:24 UTC
Labels: bug, Development, User Feedback
